/**
 * unused, just an export of all types for eventual validation
 */

export class SGFieldTypes {
  typeMap = {
    Time: true,
    string: true,
    float: true,
    boolean: true,
    'option string': true,
    time: true,
    Boolean: true,
    integer: true,
    'array of floats': true,
    ContentNode: true,
    color: true,
    uri: true,
    rect2d: true,
    Float: true,
    vector2d: true,
    font: true,
    'N/A': true,
    'array of strings': true,
    'Poster node': true,
    Font: true,
    'array of Boolean': true,
    'array of colors': true,
    ButtonGroup: true,
    Event: true,
    'array of integers': true,
    'RSGPalette node': true,
    "array of float's": true,
    Node: true,
    'option as string': true,
    'array of float': true,
    'URI string': true,
    BusySpinner: true,
    'color (string containing hex value e.g. RGBA)': true,
    'array of integer': true,
    'array of vector2d': true,
    'associative array': true,
    assocarray: true,
    bool: true,
    'associative array of associative arrays': true,
    URL: true,
    TargetSet: true,
    int: true,
    'array of TargetSet nodes': true,
    Color: true,
    'array of rectangles': true,
    'roArray of roAssociativeArrays': true,
  };
}
